### ISSUE TITLE
Code not working!

### ISSUE THREAD

**Issue by MS-Jahan** [krzesu0/MessLogger#4]
I was running this on pythonanywhere. The last file (message log) was written on 19 November, 2019. Now the code is not working. Even though I get no error, file (message log) is not being written. I've also tried running the code locally.

Please fix this.

**Comment by leventebartha** [comment]
Hi, I have a same issue, there is a missing module:
In terminal : ... python3 main.py
Traceback (most recent call last):
  File "/........./MessLogger-master/main.py", line 2, in <module>
    from Logger.logger import Logger
  File "/......../MessLogger-master/Logger/logger.py", line 1, in <module>
    from fbchat import Client, Message, ThreadType, ImageAttachment
ModuleNotFoundError: No module named 'fbchat'

**Comment by rochonastore** [comment]
> Hi, I have a same issue, there is a missing module:
> In terminal : ... python3 main.py
> Traceback (most recent call last):
> File "/........./MessLogger-master/main.py", line 2, in
> from Logger.logger import Logger
> File "/......../MessLogger-master/Logger/logger.py", line 1, in
> from fbchat import Client, Message, ThreadType, ImageAttachment
> ModuleNotFoundError: No module named 'fbchat'

Install fbchat from pip:
`pip install fbchat`

**Comment by MS-Jahan** [comment]
> Hi, I have a same issue, there is a missing module:
> In terminal : ... python3 main.py
> Traceback (most recent call last):
> File "/........./MessLogger-master/main.py", line 2, in
> from Logger.logger import Logger
> File "/......../MessLogger-master/Logger/logger.py", line 1, in
> from fbchat import Client, Message, ThreadType, ImageAttachment
> ModuleNotFoundError: No module named 'fbchat'


Install fbchat from pip:
`pip install fbchat`
